#!/bin/sh
#
# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#

echo "*************************************"
TMP_COMMIT_FILE=./commit_tmp

if [ -f $TMP_COMMIT_FILE ]; then
	TYPE=`cat $TMP_COMMIT_FILE`
	if [[ $TYPE == "NPM" ]]; then
		git add "./*package.json"
		git add "./*package-lock.json"
	else 
		git add "./*pom.xml"
	fi
    rm -f $TMP_COMMIT_FILE
    git commit --amend -C HEAD --no-verify
fi
exit 0
echo "*************************************"